# Домашнее задание

Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

Задание 3
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

Задание 4
В материалах занятия раздел “Задача 4 домашнего задания”


### Задание 1 
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [2]:
import numpy as np

In [31]:
N = int(input(' число до 100 '))
d = (np.arange((N-1), -1, -1))
print((d))

 число до 100 6
[5 4 3 2 1 0]


### Задание 2 
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [32]:
np.diag(d)

array([[5, 0, 0, 0, 0, 0],
       [0, 4, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0]])

In [29]:
tot = np.sum(d)

In [30]:
print(tot)

21


### Задание 3
Решите систему уравнений: 

    4x + 2y + z = 4 
    
    x + 3y = 12 
    
    5y + 4z = -3

In [19]:
a = np.array( [ [4, 2, 1], [1, 3, 0], [5, 4, 0] ] )

In [20]:
b = np.array( [ [4], [12], [-3] ] )

In [21]:
from numpy import linalg

In [22]:
# метод с курса
linalg.solve(a, b)

array([[-5.18181818],
       [ 5.72727273],
       [13.27272727]])

In [26]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True

In [25]:
# метод с гугла
X = np.linalg.inv(a).dot(b)

print(X)

[[-5.18181818]
 [ 5.72727273]
 [13.27272727]]


### Задание 4
В материалах занятия раздел “Задача 4 домашнего задания”
Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем

In [31]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

In [32]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [37]:
print(users_stats.shape)

(10, 6)


In [38]:
def cosine( users_stats, next_user_stats):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm( users_stats )
    bLength = np.linalg.norm( next_user_stats )
    
    return np.dot(users_stats, next_user_stats) / ( aLength * bLength )

In [39]:
cosine( users_stats, next_user_stats)

array([[1.73458675],
       [1.87522892],
       [3.18788917]])

### Комментарий
Задание 4 не совсем понял как искать значения по множествам, как присвоить ID каждой строке чтобы вывести строку нынешнего клиента с новым клиентом. Потратил 3 часа на поиск, что совсем не эффективно. 